name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
<<<<<<< HEAD
=======

>>>>>>> b7668819558b2b6e3d946c895c7c3600ad0cabd9
    steps:
    - name: ⬇️ Checkout репозиторій
      uses: actions/checkout@v3

    - name: 🐍 Встановити Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: 📦 Встановити залежності
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-html flake8 flake8-html

    - name: ✅ Запустити тести з HTML-звітом
      run: |
        mkdir -p test-reports
<<<<<<< HEAD
        pytest --html=test-reports/report.html --self-contained-html || echo "::set-output name=test_status::❌ Тести провалено"
      id: run_tests
=======
        pytest --html=test-reports/report.html --self-contained-html
>>>>>>> b7668819558b2b6e3d946c895c7c3600ad0cabd9

    - name: 🧹 Перевірка стилю коду з flake8
      run: |
        mkdir -p lint-reports
<<<<<<< HEAD
        flake8 . --format=html --htmldir=lint-reports || echo "::set-output name=lint_status::⚠️ Лінтінг знайшов проблеми"
      id: run_lint

    - name: 📤 Завантажити звіт про тести
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: test-reports/

    - name: 📤 Завантажити звіт про лінтінг
      uses: actions/upload-artifact@v4
      with:
        name: flake8-report
        path: lint-reports/

    - name: 📝 Додати коментар до Pull Request
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const testStatus = "✅ Тести виконані успішно";
          const lintStatus = "✅ Лінтінг успішний (або з попередженнями)";
          const body = `### 🧪 CI-звіт

- ${testStatus}
- ${lintStatus}

Звіти завантажено як артефакти. 🎉`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
=======
        flake8 . --format=html --htmldir=lint-reports

    - name: 📤 Завантажити артефакти (звіти)
      uses: actions/upload-artifact@v4
      with:
        name: test-lint-reports
        path: |
          test-reports/
          lint-reports/
>>>>>>> b7668819558b2b6e3d946c895c7c3600ad0cabd9
